[package]
name = "per-logparser2"
version = "0.1.0"
edition = "2024"

[dependencies]
can_unpack = { git = "https://github.com/LelsersLasers/can_unpack" }
can-dbc = "6.0.0"
clap = { version = "4.3", features = ["derive"] }
csv = "1.3.1"
log = "0.4"
env_logger = "0.11"
